apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-rollout
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: guestbook
  source:
    repoURL: https://github.com/DPP-2026/Argocd.git
    targetRevision: main
    path: manifests/guestbook-rollout
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
